parameters:
    test: abc

services:
    aService:
        class: Test\ServiceA
        arguments:
            - config.db
            - %test%
            - %%escaped
    bService:
        class: Test\ServiceB
        arguments:
            - @aService
        calls:
            - [someMethod, [%test%]]